# API Gateway Service 전용 설정

server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - RequestLogging
        - AuthenticationFilter
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Member Service 라우팅 - 정확한 매칭
        - id: member-service-api-exact
          uri: lb://member-service
          predicates:
            - Path=/api/members
          filters:
            - RewritePath=/api/members, /members
            - name: CircuitBreaker
              args:
                name: member-service
                fallbackUri: forward:/fallback/member-service
            
        # Member Service 라우팅 - 하위 경로 매칭
        - id: member-service-api-sub
          uri: lb://member-service
          predicates:
            - Path=/api/members/**
          filters:
            - RewritePath=/api/members/(?<path>.*), /members/$\{path}
            - name: CircuitBreaker
              args:
                name: member-service
                fallbackUri: forward:/fallback/member-service
            
        - id: member-service-direct
          uri: lb://member-service
          predicates:
            - Path=/member-service/**
          filters:
            - RewritePath=/member-service/(?<path>.*), /$\{path}
            
        # Order Service 라우팅 - 정확한 매칭
        - id: order-service-api-exact
          uri: lb://order-service
          predicates:
            - Path=/api/orders
          filters:
            - RewritePath=/api/orders, /orders
            - name: CircuitBreaker
              args:
                name: order-service
                fallbackUri: forward:/fallback/order-service
            
        # Order Service 라우팅 - 하위 경로 매칭
        - id: order-service-api-sub
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - RewritePath=/api/orders/(?<path>.*), /orders/$\{path}
            - name: CircuitBreaker
              args:
                name: order-service
                fallbackUri: forward:/fallback/order-service
            
        - id: order-service-direct
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<path>.*), /$\{path}
            
        # Auth Service 라우팅 - 하위 경로 매칭
        - id: auth-service-api
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<path>.*), /auth/$\{path}
            - name: CircuitBreaker
              args:
                name: auth-service
                fallbackUri: forward:/fallback/auth-service
        - id: auth-service-direct
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/(?<path>.*), /$\{path}

      # 글로벌 CORS 설정
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true

# Circuit Breaker 설정
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      member-service:
        baseConfig: default
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      order-service:
        baseConfig: default
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      auth-service:
        baseConfig: default
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

# Management endpoints 활성화
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,gateway,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
    circuitbreakers:
      enabled: true
    circuitbreakerevents:
      enabled: true
  health:
    circuitbreakers:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    com.example.gateway.filter: DEBUG

security:
  jwt:
    secret: change-me-please-change-me-please-32
